site_name: Lapis - A Pelican Blog Utility
repo_url: https://github.com/dandesousa/lapis
dev_addr: 127.0.0.1:9000
theme: readthedocs
site_author: Daniel DeSousa
pages:
    - ['index.md', 'Introduction']
    - ['getting-started.md', 'User Guide', 'Getting Started']
    - ['find.md', 'Commands', 'find']
    - ['create.md', 'Commands', 'create']
    - ['tags.md', 'Commands', 'tags']
    - ['authors.md', 'Commands', 'authors']
    - ['categories.md', 'Commands', 'categories']
    - ['sync.md', 'Commands', 'sync']
    - ['newconfig.md', 'Commands', 'newconfig']
    - ['config.md', 'User Guide', '.lapis.yml Config']
